<?
$PERM["video"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["upload"]["*"]="R";
$PERM["/"]["13"]="T_10";
$PERM["/"]["12"]="R";
$PERM["/"]["*"]="D";
$PERM["bitrix"]["12"]="R";
$PERM["about"]["9"]="T_9";
$PERM["company"]["9"]="T_9";
$PERM["pub"]["*"]="R";
?>